package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Cout_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.data$S_E9));
    tgs.append("$");
    tgs.newLine();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink data$S_E9 = MetaAdapterFactory.getContainmentLink(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a0a665adL, 0xb487408a0a665b0L, "data");
  }
}
