package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class NetworkMockClient_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("[");
    tgs.append(String.valueOf(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.id$q590)));
    tgs.append("|");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.address$qbt0));
    tgs.append("|");
    tgs.append(String.valueOf(SPropertyOperations.getInteger(ctx.getPrimaryInput(), PROPS.port$qbtY)));
    tgs.append("]");
    tgs.newLine();
  }

  private static final class PROPS {
    /*package*/ static final SProperty id$q590 = MetaAdapterFactory.getProperty(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a09f393bL, 0xb487408a09f393cL, "id");
    /*package*/ static final SProperty address$qbt0 = MetaAdapterFactory.getProperty(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a09f396fL, 0xb487408a09f3970L, "address");
    /*package*/ static final SProperty port$qbtY = MetaAdapterFactory.getProperty(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a09f396fL, 0xb487408a09f3972L, "port");
  }
}
