package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ReceiveTransaction_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.data$Dp70));
    tgs.append("<");
    tgs.newLine();
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink data$Dp70 = MetaAdapterFactory.getContainmentLink(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a0a17642L, 0xb487408a0a176ddL, "data");
  }
}
