package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class ServiceScript_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.description$pYNX));
    tgs.append(":");
    tgs.newLine();
    tgs.newLine();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.statements$pYOV)) {
      tgs.appendNode(item);
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty description$pYNX = MetaAdapterFactory.getProperty(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a09f3902L, 0xb487408a09f3906L, "description");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink statements$pYOV = MetaAdapterFactory.getContainmentLink(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a09f3902L, 0xb487408a09f3908L, "statements");
  }
}
