package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Stop_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("[");
    tgs.append(String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.network_mock$qkCw), PROPS.id$q590)));
    tgs.append("]");
    tgs.append("%");
    tgs.newLine();
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink network_mock$qkCw = MetaAdapterFactory.getReferenceLink(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a09f3a16L, 0xb487408a09f3a17L, "network_mock");
  }

  private static final class PROPS {
    /*package*/ static final SProperty id$q590 = MetaAdapterFactory.getProperty(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a09f393bL, 0xb487408a09f393cL, "id");
  }
}
