package NewLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public class TransactionStatement_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("[");
    tgs.append(String.valueOf(SPropertyOperations.getInteger(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.network_mock$DgE0), PROPS.id$q590)));
    tgs.append("]");
    tgs.newLine();
    for (SNode item : SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.transactions$DgEY)) {
      tgs.appendNode(item);
    }
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink network_mock$DgE0 = MetaAdapterFactory.getReferenceLink(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a0a17645L, 0xb487408a0a17646L, "network_mock");
    /*package*/ static final SContainmentLink transactions$DgEY = MetaAdapterFactory.getContainmentLink(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a0a17645L, 0xb487408a0a17648L, "transactions");
  }

  private static final class PROPS {
    /*package*/ static final SProperty id$q590 = MetaAdapterFactory.getProperty(0xbccde9bf61a047d3L, 0xac545528183d161bL, 0xb487408a09f393bL, 0xb487408a09f393cL, "id");
  }
}
